
language: cpp

matrix:
    include:
        - os: linux
          dist: xenial
          env:
          - LD_LIBRARY_PATH=lib
          compiler: clang
          addons:
            apt:
              packages:
                - graphviz
        - os: osx
          env:
          - LD_LIBRARY_PATH=lib
          compiler: clang
        - os: windows
          compiler: MinGW
        - os: windows
          compiler: msvc

script:
- cmake .
- cmake --build .
- cmake --build . --target package
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake --build . --target doc; fi

deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T alpha_hello-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -udinsul:$BINTRAY_API_KEY "https://api.bintray.com/content/alpha/homeworks/package/$TRAVIS_BUILD_NUMBER/alpha_hello-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

  #- |
    #if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      #- provider: pages
        #skip-cleanup: true
        #github-token: $GITHUB_TOKEN
        #keep-history: true
        #local-dir: doc/html
        #on:
          #branch: master
    #fi
