os: windows
language: cpp
compiler: gcc
script:
  #- dir
  #- pip install conan
  #- conan
  - dir
  - cmake -DCMAKE_C_COMPILER:STRING="gcc"
  - cmake -DCMAKE_CXX_COMPILER:STRING="g++"
  - cmake .
  - dir
  - cmake --build .
  - ./alpha_hello
  - cmake --build . --target package
  - dir
  #deploy:
  #- provider: script
    #skip_cleanup: true
    #script:
    #- curl -T alpha_hello.exe -udinsul:$BINTRAY_API_KEY https://api.bintray.com/content/alpha/pentapod/<YOUR_COOL_PACKAGE_NAME>/<VERSION_NAME>/<FILE_TARGET_PATH>
