os: windows
language: 
  - cpp
  - python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
compiler:
  - MinGW
  - Visual Studio
script:
  - dir
  - pip install conan
  - conan
  - dir
  - cmake .
  - dir
  - cmake --build .
  - dir
  - cmake --build . --target package
  - dir
  #deploy:
  #- provider: script
    #skip_cleanup: true
    #script:
    #- curl -T alpha_hello.exe -udinsul:$BINTRAY_API_KEY https://api.bintray.com/content/alpha/pentapod/<YOUR_COOL_PACKAGE_NAME>/<VERSION_NAME>/<FILE_TARGET_PATH>
